### =========================================================
### API TESTING SUITE
### =========================================================

### 1. REFRESH SESSION (If your access token expires)
POST http://localhost:3000/auth/refresh
Content-Type: application/json

{
  "refresh_token": "PASTE_YOUR_REFRESH_TOKEN_HERE"
}

### =========================================================
### CORE PROFILES API (Requires Authorization)
### =========================================================

### 2. Get All Profiles (Basic Read)
GET http://localhost:3000/api/profiles
X-API-Version: 1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxOWRkNDQ5LTFjY2QtNzg4YS05MWNmLWVhNDdiN2U1MDJhYyIsInJvbGUiOiJhbmFseXN0IiwiaWF0IjoxNzc3MzkwMDQzLCJleHAiOjE3NzczOTM2NDN9.pFUpt1xqB5zEptCnoKlK3pJatKdASKnpnz8NnN9xExU

### 3. Create a New Profile (Admin Only Test)
POST http://localhost:3000/api/profiles
X-API-Version: 1
Authorization: Bearer PASTE_YOUR_TOKEN_HERE
Content-Type: application/json

{
    "name": "olawunmi",
    "gender": "female",
    "age": 28,
    "country_id": "NG"
}

### 4. Get a Single Profile by ID
### (Replace the ID at the end with a real one from the GET request above)
GET http://localhost:3000/api/profiles/019db071-9afc-7331-8fbd-13ea51a9c6be
X-API-Version: 1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxOWRkNDQ5LTFjY2QtNzg4YS05MWNmLWVhNDdiN2U1MDJhYyIsInJvbGUiOiJhbmFseXN0IiwiaWF0IjoxNzc3MzkwMDQzLCJleHAiOjE3NzczOTM2NDN9.pFUpt1xqB5zEptCnoKlK3pJatKdASKnpnz8NnN9xExU

### 5. Delete a Profile by ID (Admin Only Test)
DELETE http://localhost:3000/api/profiles/019db071-073d-7995-bc5c-632cd951322d
X-API-Version: 1
Authorization: Bearer PASTE_YOUR_TOKEN_HERE

### =========================================================
### ADVANCED FEATURES (Requires Authorization)
### =========================================================

### 6. Standard Slicer (Filter & Paginate)
GET http://localhost:3000/api/profiles?gender=female&min_age=25&page=1&limit=5
X-API-Version: 1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxOWRkNDQ5LTFjY2QtNzg4YS05MWNmLWVhNDdiN2U1MDJhYyIsInJvbGUiOiJhbmFseXN0IiwiaWF0IjoxNzc3MzkwMDQzLCJleHAiOjE3NzczOTM2NDN9.pFUpt1xqB5zEptCnoKlK3pJatKdASKnpnz8NnN9xExU

### 7. Natural Language Translator Search
GET http://localhost:3000/api/profiles/search?q=females above 30 from nigeria
X-API-Version: 1
Authorization: Bearer PASTE_YOUR_TOKEN_HERE

### 8. Export to CSV (Filtered to females only)
GET http://localhost:3000/api/profiles/export?format=csv&gender=female
X-API-Version: 1
Authorization: Bearer PASTE_YOUR_TOKEN_HERE